telegram:
  api_id: 00000000000
  api_hash: "REPLACE-WITH-TELEGRAM-API-HASH"
  token: "REPLACE-WITH-TELEGRAM-TOKEN"
  lang_code: !!str "en"
  max_upload_tasks: 5
  url_validation_regexes:
    - "^http(s)?:\\/\\/.+$"
  allowed_users:  # Multiple users/groups are allowed.
    - id: 11111111111  # User or group ID.
      is_admin: !!bool True
      send_startup_message: !!bool True
      download_media_type: "VIDEO"
      save_to_storage: !!bool False
      use_url_regex_match: !!bool True
      upload:
        upload_video_file: !!bool False
        upload_video_max_file_size: 2147483648
        forward_to_group: !!bool False
        forward_group_id: -00000000000  # Group or channel ID.
        silent: !!bool False
        video_caption:
          include_title: !!bool True
          include_filename: !!bool False
          include_link: !!bool True
          include_size: !!bool True
      save_to_database: !!bool True
  api:
    upload_video_file: !!bool False
    upload_video_max_file_size: 2147483648
    upload_to_chat_ids:  # User, group or channel IDs.
      - 22222222222
      - -33333333333
    silent: !!bool False
    video_caption:
      include_title: !!bool True
      include_filename: !!bool False
      include_link: !!bool True
      include_size: !!bool True
ytdlp:
  version_check_enabled: !!bool True
  version_check_interval: 86400
  notify_users_on_new_version: !!bool True
  release_channel: "NIGHTLY"
